backend:
  name: git-gateway
  branch: master
  accept_roles:
    - admin
    - editor

media_folder: static/img
public_folder: /img

collections:
  - label: Songs
    name: songs
    folder: songs
    fields:
      - {label: "Name", name: "name", widget: "string"}